enum CapShape
{
	CAPSHAPE_UNKNOWN = -1,
	CAPSHAPE_BELL = 0,
	CAPSHAPE_CONICAL,
	CAPSHAPE_CONVEX,
	CAPSHAPE_FLAT,
	CAPSHAPE_KNOBBED,
	CAPSHAPE_SUNKEN
};

enum CapSurface
{
	CAPSURFACE_UNKNOWN = -1,
	CAPSURFACE_FIBROUS = 0,
	CAPSURFACE_GROOVES,
	CAPSURFACE_SCALY,
	CAPSURFACE_SMOOTH
};

enum CapColor
{
	CAPCOLOR_UNKNOWN = -1,
	CAPCOLOR_BROWN = 0,
	CAPCOLOR_BUFF,
	CAPCOLOR_CINNAMON,
	CAPCOLOR_GRAY,
	CAPCOLOR_GREEN,
	CAPCOLOR_PINK,
	CAPCOLOR_PURPLE,
	CAPCOLOR_RED,
	CAPCOLOR_WHITE,
	CAPCOLOR_YELLOW,
};

enum Bruises
{
	BRUISES_UNKNOWN = -1,
	BRUISES_FALSE = 0,
	BRUISES_TRUE
	
};

enum Odor
{
	ODOR_UNKNOWN = -1,
	ODOR_ALMOND = 0,
	ODOR_ANISE,
	ODOR_CREOSOTE,
	ODOR_FISHY,
	ODOR_FOUL,
	ODOR_MUSTY,
	ODOR_NONE,
	ODOR_PUNGENT,
	ODOR_SPICY
};

enum GillAttachment
{
	GILLATTACHMENT_UNKOWN = -1,
	GILLATTACHMENT_ATTACHED = 0,
	GILLATTACHMENT_DESCENDING,
	GILLATTACHMENT_FREE,
	GILLATTACHMENT_NOTCHED
};

enum GillSpacing
{
	GILLSPACING_UNKOWN = -1,
	GILLSPACING_CLOSE = 0,
	GILLSPACING_CROWDED,
	GILLSPACING_DISTANT,
};

enum GillSize
{
	GILLSIZE_UNKOWN = -1,
	GILLSIZE_BROAD = 0,
	GILLSIZE_NARROW,
};

enum GillColor
{
	GILLCOLOR_UNKOWN = -1,
	GILLCOLOR_BLACK = 0,
	GILLCOLOR_BROWN,
	GILLCOLOR_BUFF,
	GILLCOLOR_CHOCOLATE,
	GILLCOLOR_GRAY,
	GILLCOLOR_GREEN,
	GILLCOLOR_ORANGE,
	GILLCOLOR_PINK,
	GILLCOLOR_PURPLE,
	GILLCOLOR_RED,
	GILLCOLOR_WHITE,
	GILLCOLOR_YELLOW
};

enum StalkShape
{
	STALKSHAPE_UNKNOWN = -1,
	STALKSHAPE_ENLARGING = 0,
	STALKSHAPE_TAPERING,
};

enum StalkRoot
{
	STALKROOT_UNKNOWN = -1,
	STALKROOT_BULBOUS = 0,
	STALKROOT_CLUB,
	STALKROOT_CUP,
	STALKROOT_EQUAL,
	STALKROOT_RHIZOMORPHS,
	STALKROOT_ROOTED,
	STALKROOT_MISSING
};

enum StalkSurfaceAboveRing
{
	STALKSURFACE_ABOVE_RING_UNKNOWN = -1,
	STALKSURFACE_ABOVE_RING_FIBROUS = 0,
	STALKSURFACE_ABOVE_RING_SCALY,
	STALKSURFACE_ABOVE_RING_SILKY,
	STALKSURFACE_ABOVE_RING_SMOOTH
};

enum StalkSurfaceBelowRing
{
	STALKSURFACE_BELOW_RING_UNKNOWN = -1,
	STALKSURFACE_BELOW_RING_FIBROUS = 0,
	STALKSURFACE_BELOW_RING_SCALY,
	STALKSURFACE_BELOW_RING_SILKY,
	STALKSURFACE_BELOW_RING_SMOOTH
};

enum StalkColorAboveRing
{
	STALKCOLOR_ABOVE_RING_UNKNOWN = -1,
	STALKCOLOR_ABOVE_RING_BROWN = 0,
	STALKCOLOR_ABOVE_RING_BUFF,
	STALKCOLOR_ABOVE_RING_CINNAMON,
	STALKCOLOR_ABOVE_RING_GRAY,
	STALKCOLOR_ABOVE_RING_ORANGE,
	STALKCOLOR_ABOVE_RING_PINK,
	STALKCOLOR_ABOVE_RING_RED,
	STALKCOLOR_ABOVE_RING_WHITE,
	STALKCOLOR_ABOVE_RING_YELLOW
};

enum StalkColorBelowRing
{
	STALKCOLOR_BELOW_RING_UNKNOWN = -1,
	STALKCOLOR_BELOW_RING_BROWN = 0,
	STALKCOLOR_BELOW_RING_BUFF,
	STALKCOLOR_BELOW_RING_CINNAMON,
	STALKCOLOR_BELOW_RING_GRAY,
	STALKCOLOR_BELOW_RING_ORANGE,
	STALKCOLOR_BELOW_RING_PINK,
	STALKCOLOR_BELOW_RING_RED,
	STALKCOLOR_BELOW_RING_WHITE,
	STALKCOLOR_BELOW_RING_YELLOW
};

enum VeilType
{
	VEILTYPE_UNKNOWN = -1,
	VEILTYPE_PARTIAL = 0,
	VEILTYPE_UNIVERSAL
};

enum VeilColor
{
	VEILCOLOR_UNKNOWN = -1,
	VEILCOLOR_BROWN = 0,
	VEILCOLOR_ORANGE,
	VEILCOLOR_WHITE,
	VEILCOLOR_YELLOW
};

enum RingNumber
{
	RINGNUMBER_UNKNOWN = -1,
	RINGNUMBER_ONE,
	RINGNUMBER_TWO
};

enum RingType
{
	RINGTYPE_UNKNOWN = -1,
	RINGTYPE_COBWEBBY = 0,
	RINGTYPE_EVANESCENT,
	RINGTYPE_FLARING,
	RINGTYPE_LARGE,
	RINGTYPE_NONE,
	RINGTYPE_PENDANT,
	RINGTYPE_SHEATHING,
	RINGTYPE_ZONE
};

enum SporePrintColor
{
	SPOREPRINTCOLOR_UNKNOWN = -1,
	SPOREPRINTCOLOR_BLACK = 0,
	SPOREPRINTCOLOR_BROWN,
	SPOREPRINTCOLOR_BUFF,
	SPOREPRINTCOLOR_CHOCOLATE,
	SPOREPRINTCOLOR_GREEN,
	SPOREPRINTCOLOR_ORANGE,
	SPOREPRINTCOLOR_PURPLE,
	SPOREPRINTCOLOR_WHITE,
	SPOREPRINTCOLOR_YELLOW
};

enum Population
{
	POPULATION_UNKNOWN = -1,
	POPULATION_ABUNDANT = 0,
	POPULATION_CLUSTERED,
	POPULATION_NUMEROUS,
	POPULATION_SCATTERED,
	POPULATION_SEVERAL,
	POPULATION_SOLITARY
};

enum Habitat
{
	HABITAT_UNKNOWN = -1,
	HABITAT_GRASSES = 0,
	HABITAT_LEAVES,
	HABITAT_MEADOWS,
	HABITAT_PATHS,
	HABITAT_URBAN,
	HABITAT_WASTE,
	HABITAT_WOODS
};